[package]
name = "bc_p2p"
version = "0.1.0"
authors = ["corihle"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
libp2p = "0.18.1"
async-std = "1.5.0"
env_logger = "0.7.1"
chrono = "0.4.11"